Add conditional MATLAB installation to Dockerfile and update devcontainer.json

diff --git a/.devcontainer/Dockerfile b/.devcontainer/Dockerfile
--- a/.devcontainer/Dockerfile
+++ b/.devcontainer/Dockerfile
@@ -26,68 +26,68 @@ RUN chmod -R 555 /data/
 FROM ${DEVCONTAINER_BASE} AS devcontainer
 
 #########################################################
-# Install Matlab
+# Install Matlab (conditional on INSTALL_MATLAB build arg)
 #   Based on mathworks/{matlab-deps:r2023b,matlab:r2023b}
 #
 # Configure the Matlab License Server to use Matlab within the devcontainer (including VSCode extensions):
 #   In your HOST environment, export the environment variable MATLAB_LICENSE_FILE, e.g.
 #       export MATLAB_LICENSE_FILE=/mnt/c/Users/username/Documents/MATLAB/license.lic
+#
+# To skip MATLAB installation, set the INSTALL_MATLAB build arg to "false" in devcontainer.json.
 #########################################################
 
 ENV DEBIAN_FRONTEND="noninteractive" TZ="Etc/UTC"
 
-COPY --from=file-normalizer /data/matlab-r2023b.ubuntu-22.04.dependencies.txt /tmp/matlab-dependencies.txt
-
-RUN export DEBIAN_FRONTEND=noninteractive \
-    && apt-get update \
-    && apt-get install --no-install-recommends --yes \
-    `cat /tmp/matlab-dependencies.txt` \
-    wget \
-    unzip \
-    ca-certificates \
-    && apt-get clean \
-    && apt-get -y autoremove \
-    && rm -rf /var/lib/apt/lists/*
-
-RUN [ -d /usr/share/X11/xkb ] || mkdir -p /usr/share/X11/xkb
-
+ARG INSTALL_MATLAB=true
 ARG MATLAB_RELEASE=r2023b
 ARG MATLAB_PRODUCT_LIST="MATLAB"
 ARG MATLAB_INSTALL_LOCATION="/opt/matlab/${MATLAB_RELEASE}"
 ARG LICENSE_SERVER=
 
-RUN adduser --shell /bin/bash --disabled-password --gecos "" matlab \
-    && echo "matlab ALL=(ALL) NOPASSWD: ALL" > /etc/sudoers.d/matlab \
-    && chmod 0440 /etc/sudoers.d/matlab
-
-USER matlab
-WORKDIR /home/matlab
-
 ENV MLM_LICENSE_FILE=${LICENSE_SERVER}
 
-RUN wget -q https://www.mathworks.com/mpm/glnxa64/mpm \
-    && chmod +x mpm \
-    && sudo HOME=${HOME} ./mpm install \
-    --release=${MATLAB_RELEASE} \
-    --destination=${MATLAB_INSTALL_LOCATION} \
-    --products ${MATLAB_PRODUCT_LIST} \
-    || (echo "MPM Installation Failure. See below for more information:" && cat /tmp/mathworks_root.log && false) \
-    && sudo rm -f mpm /tmp/mathworks_root.log \
-    && sudo ln -s ${MATLAB_INSTALL_LOCATION}/bin/matlab /usr/local/bin/matlab \
-    && sudo ln -s ${MATLAB_INSTALL_LOCATION} /opt/matlab/latest \
-    && sudo mkdir -p ${MATLAB_INSTALL_LOCATION}/licenses
+COPY --from=file-normalizer /data/matlab-r2023b.ubuntu-22.04.dependencies.txt /tmp/matlab-dependencies.txt
 
-# Install workaround run-matlab-command script to unify local and CI invocations of `matlab -batch`
-# See https://github.com/matlab-actions/run-command/issues/53
-RUN sudo wget -O /usr/local/bin/run-matlab-command https://ssd.mathworks.com/supportfiles/ci/run-matlab-command/v2/glnxa64/run-matlab-command \
-    && sudo chmod +x /usr/local/bin/run-matlab-command
+RUN if [ "${INSTALL_MATLAB}" = "true" ]; then \
+        set -e; \
+        export DEBIAN_FRONTEND=noninteractive; \
+        apt-get update; \
+        apt-get install --no-install-recommends --yes \
+            $(cat /tmp/matlab-dependencies.txt) \
+            wget \
+            unzip \
+            ca-certificates; \
+        apt-get clean; \
+        apt-get -y autoremove; \
+        rm -rf /var/lib/apt/lists/*; \
+        [ -d /usr/share/X11/xkb ] || mkdir -p /usr/share/X11/xkb; \
+        adduser --shell /bin/bash --disabled-password --gecos "" matlab; \
+        echo "matlab ALL=(ALL) NOPASSWD: ALL" > /etc/sudoers.d/matlab; \
+        chmod 0440 /etc/sudoers.d/matlab; \
+        cd /home/matlab; \
+        wget -q https://www.mathworks.com/mpm/glnxa64/mpm -O /home/matlab/mpm; \
+        chmod +x /home/matlab/mpm; \
+        HOME=/home/matlab /home/matlab/mpm install \
+            --release=${MATLAB_RELEASE} \
+            --destination=${MATLAB_INSTALL_LOCATION} \
+            --products ${MATLAB_PRODUCT_LIST} \
+            || (echo "MPM Installation Failure. See below for more information:" && cat /tmp/mathworks_root.log && false); \
+        rm -f /home/matlab/mpm /tmp/mathworks_root.log; \
+        ln -s ${MATLAB_INSTALL_LOCATION}/bin/matlab /usr/local/bin/matlab; \
+        ln -s ${MATLAB_INSTALL_LOCATION} /opt/matlab/latest; \
+        mkdir -p ${MATLAB_INSTALL_LOCATION}/licenses; \
+        chown -R matlab:matlab /opt/matlab; \
+        wget -O /usr/local/bin/run-matlab-command https://ssd.mathworks.com/supportfiles/ci/run-matlab-command/v2/glnxa64/run-matlab-command; \
+        chmod +x /usr/local/bin/run-matlab-command; \
+    else \
+        echo "Skipping MATLAB installation (INSTALL_MATLAB=${INSTALL_MATLAB})"; \
+    fi
 
 
 #########################################################
 # Install everything else
 #########################################################
 
-USER root
 
 # Install needed packages and setup non-root user.
 ARG USERNAME="vscode"
@@ -152,7 +152,7 @@ ENV GOROOT="/usr/local/go"
 ENV GOPATH="/go"
 ENV "PATH"="/usr/local/go/bin:/go/bin:${PATH}"
 RUN umask 0002 \
-    && script=$(curl -fsSL "https://raw.githubusercontent.com/devcontainers/features/8d3685e09f18dd8b0a6bce50abe3e868dac27a69/src/go/install.sh") \
+    && script=$(curl -fsSL "https://raw.githubusercontent.com/devcontainers/features/8c471574f1b39e260e88ddcb858ab1681dafbdac/src/go/install.sh") \
     && VERSION=${GO_VERSION} TARGET_GOPATH=${GOPATH} TARGET_GOROOT=${GOROOT} bash -c "$script" \
     && chown -R "${USERNAME}:conda" "${GOROOT}" "${GOPATH}"
 
